[project]
name = "tasks"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
	"beautifulsoup4>=4.13.3",
	"pymongo>=4.11.1",
	"selenium>=4.28.1",
]
